
var wpAjaxUrl='https://thsfuture.se/wp-admin/admin-ajax.php';var flBuilderUrl='https://thsfuture.se/wp-content/plugins/bb-plugin/';var FLBuilderLayoutConfig={anchorLinkAnimations:{duration:1000,easing:'swing',offset:100},paths:{pluginUrl:'https://thsfuture.se/wp-content/plugins/bb-plugin/',wpAjaxUrl:'https://thsfuture.se/wp-admin/admin-ajax.php'},breakpoints:{small:768,medium:992},waypoint:{offset:80}};(function($){if(typeof FLBuilderLayout!='undefined'){return;}
FLBuilderLayout={init:function()
{FLBuilderLayout._destroy();FLBuilderLayout._initClasses();FLBuilderLayout._initBackgrounds();if(0===$('.fl-builder-edit').length){FLBuilderLayout._initAnchorLinks();FLBuilderLayout._initHash();FLBuilderLayout._initModuleAnimations();FLBuilderLayout._initForms();}},refreshGalleries:function(element)
{var $element='undefined'==typeof element?$('body'):$(element),mfContent=$element.find('.fl-mosaicflow-content'),wmContent=$element.find('.fl-gallery'),mfObject=null;if(mfContent){mfObject=mfContent.data('mosaicflow');if(mfObject){mfObject.columns=$([]);mfObject.columnsHeights=[];mfContent.data('mosaicflow',mfObject);mfContent.mosaicflow('refill');}}
if(wmContent){wmContent.trigger('refreshWookmark');}},refreshGridLayout:function(element)
{var $element='undefined'==typeof element?$('body'):$(element),msnryContent=$element.find('.masonry');if(msnryContent.length){msnryContent.masonry('layout');}},reloadSlider:function(element)
{var $element='undefined'==typeof element?$('body'):$(element),bxContent=$element.find('.bx-viewport > div').eq(0),bxObject=null;if(bxContent.length){bxObject=bxContent.data('bxSlider');if(bxObject){bxObject.reloadSlider();}}},resizeAudio:function(element)
{var $element='undefined'==typeof element?$('body'):$(element),audioPlayers=$element.find('.wp-audio-shortcode.mejs-audio'),player=null,mejsPlayer=null,rail=null,railWidth=400;if(audioPlayers.length&&typeof mejs!=='undefined'){audioPlayers.each(function(){player=$(this);mejsPlayer=mejs.players[player.attr('id')];rail=player.find('.mejs-controls .mejs-time-rail');var innerMejs=player.find('.mejs-inner'),total=player.find('.mejs-controls .mejs-time-total');if(typeof mejsPlayer!=='undefined'){railWidth=Math.ceil(player.width()*0.8);if(innerMejs.length){rail.css('width',railWidth+'px!important');mejsPlayer.options.autosizeProgress=true;setTimeout(function(){mejsPlayer.setControlsSize();},50);player.find('.mejs-inner').css({visibility:'visible',height:'inherit'});}}});}},preloadAudio:function(element)
{var $element='undefined'==typeof element?$('body'):$(element),contentWrap=$element.closest('.fl-accordion-item'),audioPlayers=$element.find('.wp-audio-shortcode.mejs-audio');if(!contentWrap.hasClass('fl-accordion-item-active')&&audioPlayers.find('.mejs-inner').length){audioPlayers.find('.mejs-inner').css({visibility:'hidden',height:0});}},resizeSlideshow:function(){if(typeof YUI!=='undefined'){YUI().use('node-event-simulate',function(Y){Y.one(window).simulate("resize");});}},_destroy:function()
{var win=$(window);win.off('scroll.fl-bg-parallax');win.off('resize.fl-bg-video');},_isTouch:function()
{if(('ontouchstart'in window)||(window.DocumentTouch&&document instanceof DocumentTouch)){return true;}
return false;},_isMobile:function()
{return/Mobile|Android|Silk\/|Kindle|BlackBerry|Opera Mini|Opera Mobi|webOS/i.test(navigator.userAgent);},_initClasses:function()
{var body=$('body'),ua=navigator.userAgent;if(!body.hasClass('archive')&&$('.fl-builder-content-primary').length>0){body.addClass('fl-builder');}
if(FLBuilderLayout._isTouch()){body.addClass('fl-builder-touch');}
if(FLBuilderLayout._isMobile()){body.addClass('fl-builder-mobile');}
if(ua.indexOf('Trident/7.0')>-1&&ua.indexOf('rv:11.0')>-1){body.addClass('fl-builder-ie-11');}},_initBackgrounds:function()
{var win=$(window);if($('.fl-row-bg-parallax').length>0&&!FLBuilderLayout._isMobile()){FLBuilderLayout._scrollParallaxBackgrounds();FLBuilderLayout._initParallaxBackgrounds();win.on('scroll.fl-bg-parallax',FLBuilderLayout._scrollParallaxBackgrounds);}
if($('.fl-bg-video').length>0){FLBuilderLayout._initBgVideos();FLBuilderLayout._resizeBgVideos();win.on('resize.fl-bg-video',FLBuilderLayout._resizeBgVideos);}},_initParallaxBackgrounds:function()
{$('.fl-row-bg-parallax').each(FLBuilderLayout._initParallaxBackground);},_initParallaxBackground:function()
{var row=$(this),content=row.find('> .fl-row-content-wrap'),src=row.data('parallax-image'),loaded=row.data('parallax-loaded'),img=new Image();if(loaded){return;}
else if(typeof src!='undefined'){$(img).on('load',function(){content.css('background-image','url('+src+')');row.data('parallax-loaded',true);});img.src=src;}},_scrollParallaxBackgrounds:function()
{$('.fl-row-bg-parallax').each(FLBuilderLayout._scrollParallaxBackground);},_scrollParallaxBackground:function()
{var win=$(window),row=$(this),content=row.find('> .fl-row-content-wrap'),speed=row.data('parallax-speed'),offset=content.offset(),yPos=-((win.scrollTop()-offset.top)/speed);content.css('background-position','center '+yPos+'px');},_initBgVideos:function()
{$('.fl-bg-video').each(FLBuilderLayout._initBgVideo);},_initBgVideo:function()
{var wrap=$(this),width=wrap.data('width'),height=wrap.data('height'),mp4=wrap.data('mp4'),youtube=wrap.data('youtube'),vimeo=wrap.data('vimeo'),mp4Type=wrap.data('mp4-type'),webm=wrap.data('webm'),webmType=wrap.data('webm-type'),fallback=wrap.data('fallback'),loaded=wrap.data('loaded'),fallbackTag='',videoTag=null,mp4Tag=null,webmTag=null;if(loaded){return;}
videoTag=$('<video autoplay loop muted playsinline></video>');if('undefined'!=typeof fallback&&''!=fallback){videoTag.attr('poster','data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7')
videoTag.css('background','transparent url("'+fallback+'") no-repeat center center')
videoTag.css('background-size','cover')
videoTag.css('height','100%')}
if('undefined'!=typeof mp4&&''!=mp4){mp4Tag=$('<source />');mp4Tag.attr('src',mp4);mp4Tag.attr('type',mp4Type);videoTag.append(mp4Tag);}
if('undefined'!=typeof webm&&''!=webm){webmTag=$('<source />');webmTag.attr('src',webm);webmTag.attr('type',webmType);videoTag.append(webmTag);}
if('undefined'!=typeof youtube&&!FLBuilderLayout._isMobile()){FLBuilderLayout._initYoutubeBgVideo.apply(this);}
else if('undefined'!=typeof vimeo&&!FLBuilderLayout._isMobile()){FLBuilderLayout._initVimeoBgVideo.apply(this);}
else{wrap.append(videoTag);}
wrap.data('loaded',true);},_initYoutubeBgVideo:function()
{var playerWrap=$(this),videoId=playerWrap.data('video-id'),videoPlayer=playerWrap.find('.fl-bg-video-player'),enableAudio=playerWrap.data('enable-audio'),audioButton=playerWrap.find('.fl-bg-video-audio'),startTime='undefined'!==typeof playerWrap.data('t')?playerWrap.data('t'):0,loop='undefined'!==typeof playerWrap.data('loop')?playerWrap.data('loop'):1,vidPlayed=false,didUnmute=false,stateCount=0,player;if(videoId){FLBuilderLayout._onYoutubeApiReady(function(YT){setTimeout(function(){player=new YT.Player(videoPlayer[0],{videoId:videoId,events:{onReady:function(event){if("no"===enableAudio){event.target.mute();}
else if("yes"===enableAudio&&event.target.isMuted){event.target.unMute();}
playerWrap.data('YTPlayer',player);FLBuilderLayout._resizeYoutubeBgVideo.apply(playerWrap);event.target.playVideo();if(audioButton.length>0){audioButton.on('click',{button:audioButton,player:player},FLBuilderLayout._toggleBgVideoAudio);}},onStateChange:function(event){if(stateCount<4){stateCount++;}
if(stateCount>1&&-1===event.data&&"yes"===enableAudio){player.mute();player.playVideo();audioButton.show();}
if(event.data===YT.PlayerState.ENDED&&1===loop){if(startTime>0){player.seekTo(startTime);}
else{player.playVideo();}}},onError:function(event){console.info('YT Error: '+event.data)
FLBuilderLayout._onErrorYoutubeVimeo(playerWrap)}},playerVars:{controls:0,showinfo:0,rel:0,start:startTime,}});},1);});}},_onErrorYoutubeVimeo:function(playerWrap){fallback=playerWrap.data('fallback')||false
if(!fallback){return false;}
playerWrap.find('iframe').remove()
fallbackTag=$('<div></div>');fallbackTag.addClass('fl-bg-video-fallback');fallbackTag.css('background-image','url('+playerWrap.data('fallback')+')');playerWrap.append(fallbackTag);},_onYoutubeApiReady:function(callback){if(window.YT&&YT.loaded){callback(YT);}else{setTimeout(function(){FLBuilderLayout._onYoutubeApiReady(callback);},350);}},_initVimeoBgVideo:function()
{var playerWrap=$(this),videoId=playerWrap.data('video-id'),videoPlayer=playerWrap.find('.fl-bg-video-player'),enableAudio=playerWrap.data('enable-audio'),audioButton=playerWrap.find('.fl-bg-video-audio'),player,width=playerWrap.outerWidth();if(typeof Vimeo!=='undefined'&&videoId){player=new Vimeo.Player(videoPlayer[0],{id:videoId,loop:true,title:false,portrait:false,background:true,autopause:false,muted:true});playerWrap.data('VMPlayer',player);if("no"===enableAudio){player.setVolume(0);}
else if("yes"===enableAudio){if($.browser.safari||$.browser.chrome){player.setVolume(0);audioButton.show();}
else{player.setVolume(1);}}
player.play().catch(function(error){FLBuilderLayout._onErrorYoutubeVimeo(playerWrap)});if(audioButton.length>0){audioButton.on('click',{button:audioButton,player:player},FLBuilderLayout._toggleBgVideoAudio);}}},_toggleBgVideoAudio:function(e){var player=e.data.player,control=e.data.button.find('.fl-audio-control');if(control.hasClass('fa-volume-off')){control.removeClass('fa-volume-off').addClass('fa-volume-up');e.data.button.find('.fa-times').hide();if('function'===typeof player.unMute){player.unMute();}
else{player.setVolume(1);}}
else{control.removeClass('fa-volume-up').addClass('fa-volume-off');e.data.button.find('.fa-times').show();if('function'===typeof player.unMute){player.mute();}
else{player.setVolume(0);}}},_videoBgSourceError:function(e)
{var source=$(e.target),wrap=source.closest('.fl-bg-video'),vid=wrap.find('video'),fallback=wrap.data('fallback'),fallbackTag='';source.remove();if(vid.find('source').length){return;}else if(''!==fallback){fallbackTag=$('<div></div>');fallbackTag.addClass('fl-bg-video-fallback');fallbackTag.css('background-image','url('+fallback+')');wrap.append(fallbackTag);vid.remove();}},_resizeBgVideos:function()
{$('.fl-bg-video').each(function(){FLBuilderLayout._resizeBgVideo.apply(this);if($(this).parent().find('img').length>0){$(this).parent().imagesLoaded($.proxy(FLBuilderLayout._resizeBgVideo,this));}});},_resizeBgVideo:function()
{if(0===$(this).find('video').length&&0===$(this).find('iframe').length){return;}
var wrap=$(this),wrapHeight=wrap.outerHeight(),wrapWidth=wrap.outerWidth(),vid=wrap.find('video'),vidHeight=wrap.data('height'),vidWidth=wrap.data('width'),newWidth=wrapWidth,newHeight=Math.round(vidHeight*wrapWidth/vidWidth),newLeft=0,newTop=0,iframe=wrap.find('iframe');if(vid.length){if(vidHeight===''||typeof vidHeight==='undefined'||vidWidth===''||typeof vidWidth==='undefined'){vid.css({'left':'0px','top':'0px','width':newWidth+'px'});vid.on('loadedmetadata',FLBuilderLayout._resizeOnLoadedMeta);}
else{if(newHeight<wrapHeight){newHeight=wrapHeight;newWidth=Math.round(vidWidth*wrapHeight/vidHeight);newLeft=-((newWidth-wrapWidth)/2);}
else{newTop=-((newHeight-wrapHeight)/2);}
vid.css({'left':newLeft+'px','top':newTop+'px','height':newHeight+'px','width':newWidth+'px'});}}
else if(iframe.length){if(typeof wrap.data('youtube')!=='undefined'){FLBuilderLayout._resizeYoutubeBgVideo.apply(this);}}},_resizeOnLoadedMeta:function(){var video=$(this),wrapHeight=video.parent().outerHeight(),wrapWidth=video.parent().outerWidth(),vidWidth=video[0].videoWidth,vidHeight=video[0].videoHeight,newHeight=Math.round(vidHeight*wrapWidth/vidWidth),newWidth=wrapWidth,newLeft=0,newTop=0;if(newHeight<wrapHeight){newHeight=wrapHeight;newWidth=Math.round(vidWidth*wrapHeight/vidHeight);newLeft=-((newWidth-wrapWidth)/2);}
else{newTop=-((newHeight-wrapHeight)/2);}
video.parent().data('width',vidWidth);video.parent().data('height',vidHeight);video.css({'left':newLeft+'px','top':newTop+'px','width':newWidth+'px','height':newHeight+'px'});},_resizeYoutubeBgVideo:function()
{var wrap=$(this),wrapWidth=wrap.outerWidth(),wrapHeight=wrap.outerHeight(),player=wrap.data('YTPlayer'),video=player?player.getIframe():null,aspectRatioSetting='16:9',aspectRatioArray=aspectRatioSetting.split(':'),aspectRatio=aspectRatioArray[0]/aspectRatioArray[1],ratioWidth=wrapWidth/aspectRatio,ratioHeight=wrapHeight*aspectRatio,isWidthFixed=wrapWidth/wrapHeight>aspectRatio,width=isWidthFixed?wrapWidth:ratioHeight,height=isWidthFixed?ratioWidth:wrapHeight;if(video){$(video).width(width).height(height);}},_initModuleAnimations:function()
{if(typeof jQuery.fn.waypoint!=='undefined'&&!FLBuilderLayout._isMobile()){$('.fl-animation').each(function(){var node=$(this),nodeTop=node.offset().top,winHeight=$(window).height(),bodyHeight=$('body').height(),waypoint=FLBuilderLayoutConfig.waypoint,offset='80%';if(typeof waypoint.offset!==undefined){offset=FLBuilderLayoutConfig.waypoint.offset+'%';}
if(bodyHeight-nodeTop<winHeight*0.2){offset='100%';}
node.waypoint({offset:offset,handler:FLBuilderLayout._doModuleAnimation});});}},_doModuleAnimation:function()
{var module='undefined'==typeof this.element?$(this):$(this.element),delay=parseFloat(module.data('animation-delay'));if(!isNaN(delay)&&delay>0){setTimeout(function(){module.addClass('fl-animated');},delay*1000);}
else{module.addClass('fl-animated');}},_initHash:function()
{var hash=window.location.hash.replace('#','').split('/').shift(),element=null,tabs=null,responsiveLabel=null,tabIndex=null,label=null;if(''!==hash){try{element=$('#'+hash);if(element.length>0){if(element.hasClass('fl-accordion-item')){setTimeout(function(){element.find('.fl-accordion-button').trigger('click');},100);}
if(element.hasClass('fl-tabs-panel')){setTimeout(function(){tabs=element.closest('.fl-tabs');responsiveLabel=element.find('.fl-tabs-panel-label');tabIndex=responsiveLabel.data('index');label=tabs.find('.fl-tabs-labels .fl-tabs-label[data-index='+tabIndex+']');if(responsiveLabel.is(':visible')){responsiveLabel.trigger('click');}
else{label[0].click();FLBuilderLayout._scrollToElement(element);}},100);}}}
catch(e){}}},_initAnchorLinks:function()
{$('a').each(FLBuilderLayout._initAnchorLink);},_initAnchorLink:function()
{var link=$(this),href=link.attr('href'),loc=window.location,id=null,element=null;if('undefined'!=typeof href&&href.indexOf('#')>-1&&link.closest('svg').length<1){if(loc.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')&&loc.hostname==this.hostname){try{id=href.split('#').pop();if(!id){return;}
element=$('#'+id);if(element.length>0){if(link.hasClass('fl-scroll-link')||element.hasClass('fl-row')||element.hasClass('fl-col')||element.hasClass('fl-module')){$(link).on('click',FLBuilderLayout._scrollToElementOnLinkClick);}
if(element.hasClass('fl-accordion-item')){$(link).on('click',FLBuilderLayout._scrollToAccordionOnLinkClick);}
if(element.hasClass('fl-tabs-panel')){$(link).on('click',FLBuilderLayout._scrollToTabOnLinkClick);}}}
catch(e){}}}},_scrollToElementOnLinkClick:function(e,callback)
{var element=$('#'+$(this).attr('href').split('#').pop());FLBuilderLayout._scrollToElement(element,callback);e.preventDefault();},_scrollToElement:function(element,callback)
{var config=FLBuilderLayoutConfig.anchorLinkAnimations,dest=0,win=$(window),doc=$(document);if(element.length>0){if(element.offset().top>doc.height()-win.height()){dest=doc.height()-win.height();}
else{dest=element.offset().top-config.offset;}
$('html, body').animate({scrollTop:dest},config.duration,config.easing,function(){if('undefined'!=typeof callback){callback();}
if(undefined!=element.attr('id')){if(history.pushState){history.pushState(null,null,'#'+element.attr('id'));}
else{window.location.hash=element.attr('id');}}});}},_scrollToAccordionOnLinkClick:function(e)
{var element=$('#'+$(this).attr('href').split('#').pop());if(element.length>0){var callback=function(){if(element){element.find('.fl-accordion-button').trigger('click');element=false;}};FLBuilderLayout._scrollToElementOnLinkClick.call(this,e,callback);}},_scrollToTabOnLinkClick:function(e)
{var element=$('#'+$(this).attr('href').split('#').pop()),tabs=null,label=null,responsiveLabel=null;if(element.length>0){tabs=element.closest('.fl-tabs');responsiveLabel=element.find('.fl-tabs-panel-label');tabIndex=responsiveLabel.data('index');label=tabs.find('.fl-tabs-labels .fl-tabs-label[data-index='+tabIndex+']');if(responsiveLabel.is(':visible')){var callback=function(){if(element){responsiveLabel.trigger('click');element=false;}};FLBuilderLayout._scrollToElementOnLinkClick.call(this,e,callback);}
else{label[0].click();FLBuilderLayout._scrollToElement(element);}
e.preventDefault();}},_initForms:function()
{if(!FLBuilderLayout._hasPlaceholderSupport){$('.fl-form-field input').each(FLBuilderLayout._initFormFieldPlaceholderFallback);}
$('.fl-form-field input').on('focus',FLBuilderLayout._clearFormFieldError);},_hasPlaceholderSupport:function()
{var input=document.createElement('input');return'undefined'!=input.placeholder;},_initFormFieldPlaceholderFallback:function()
{var field=$(this),val=field.val(),placeholder=field.attr('placeholder');if('undefined'!=placeholder&&''===val){field.val(placeholder);field.on('focus',FLBuilderLayout._hideFormFieldPlaceholderFallback);field.on('blur',FLBuilderLayout._showFormFieldPlaceholderFallback);}},_hideFormFieldPlaceholderFallback:function()
{var field=$(this),val=field.val(),placeholder=field.attr('placeholder');if(val==placeholder){field.val('');}},_showFormFieldPlaceholderFallback:function()
{var field=$(this),val=field.val(),placeholder=field.attr('placeholder');if(''===val){field.val(placeholder);}},_clearFormFieldError:function()
{var field=$(this);field.removeClass('fl-form-error');field.siblings('.fl-form-error-message').hide();}};$(function(){FLBuilderLayout.init();});})(jQuery);(function($){$('.fl-node-5b460deae3dc1 .pp-infobox').on('mouseenter',function(){$('.fl-node-5b460deae3dc1 .pp-icon-wrapper').addClass(' none');});$('.fl-node-5b460deae3dc1 .pp-infobox').on('mouseleave',function(){$('.fl-node-5b460deae3dc1 .pp-icon-wrapper').removeClass(' none');});})(jQuery);(function($){PPAnimatedHeadlines=function(settings){this.settings=settings;this.nodeClass='.fl-node-'+settings.id;this.headline=this.nodeClass+' .pp-headline';this.dynamicWrapper=this.nodeClass+' .pp-headline-dynamic-wrapper';this.animationDelay=2500;this.lettersDelay=50;this.typeLettersDelay=150;this.selectionDuration=500;this.revealDuration=600,this.revealAnimationDelay=1500;this.typeAnimationDelay=this.selectionDuration+800;this.classes={dynamicText:'pp-headline-dynamic-text',textActive:'pp-headline-text-active',textInactive:'pp-headline-text-inactive',letters:'pp-headline-letters',animationIn:'pp-headline-animation-in',typeSelected:'pp-headline-typing-selected'};this.elements={};this._fillWords();this._initHeadlines();};PPAnimatedHeadlines.prototype={settings:{},nodeClass:'',headline:'',dynamicWrapper:'',animationDelay:2500,lettersDelay:50,typeLettersDelay:150,selectionDuration:500,revealDuration:600,revealAnimationDelay:1500,svgPaths:{circle:['M325,18C228.7-8.3,118.5,8.3,78,21C22.4,38.4,4.6,54.6,5.6,77.6c1.4,32.4,52.2,54,142.6,63.7 c66.2,7.1,212.2,7.5,273.5-8.3c64.4-16.6,104.3-57.6,33.8-98.2C386.7-4.9,179.4-1.4,126.3,20.7'],curly:['M3,146.1c17.1-8.8,33.5-17.8,51.4-17.8c15.6,0,17.1,18.1,30.2,18.1c22.9,0,36-18.6,53.9-18.6 c17.1,0,21.3,18.5,37.5,18.5c21.3,0,31.8-18.6,49-18.6c22.1,0,18.8,18.8,36.8,18.8c18.8,0,37.5-18.6,49-18.6c20.4,0,17.1,19,36.8,19 c22.9,0,36.8-20.6,54.7-18.6c17.7,1.4,7.1,19.5,33.5,18.8c17.1,0,47.2-6.5,61.1-15.6'],strikethrough:['M3,75h493.5'],underline:['M7.7,145.6C109,125,299.9,116.2,401,121.3c42.1,2.2,87.6,11.8,87.3,25.7'],underline_zigzag:['M9.3,127.3c49.3-3,150.7-7.6,199.7-7.4c121.9,0.4,189.9,0.4,282.3,7.2C380.1,129.6,181.2,130.6,70,139 c82.6-2.9,254.2-1,335.9,1.3c-56,1.4-137.2-0.3-197.1,9']},_fillWords:function()
{var classes=this.classes,dynamicWrapper=$(this.dynamicWrapper),settings=this.settings;if('rotate'==this.settings.headline_style){var rotatingText=this.settings.rotating_text.split('|');rotatingText.forEach(function(word,index){var dynamicText=$('<span>',{'class':classes.dynamicText}).html(word.replace(' ','&nbsp;'));if(!index){dynamicText.addClass(classes.textActive);}
dynamicWrapper.append(dynamicText);});}else{var dynamicText=$('<span>',{'class':classes.dynamicText+' '+classes.textActive}).text(settings.highlighted_text);var svg=$('<svg>',{xmlns:'http://www.w3.org/2000/svg',viewBox:'0 0 500 150',preserveAspectRatio:'none'}).html(this._getSvgPaths(settings.headline_shape));dynamicWrapper.append(dynamicText,svg[0].outerHTML);}
this.elements.dynamicText=dynamicWrapper.children('.'+classes.dynamicText);},_initHeadlines:function()
{if('rotate'===this.settings.headline_style){this._rotateHeadline();}},_rotateHeadline:function(){if($(this.headline).hasClass(this.classes.letters)){this._singleLetters();}
this._animateHeadline();},_singleLetters:function(){var classes=this.classes;this.elements.dynamicText.each(function(){var $word=$(this),letters=$word.text().split(''),isActive=$word.hasClass(classes.textActive);$word.empty();letters.forEach(function(letter){var $i=$('<i>').text(letter);if(isActive){$i.addClass(classes.animationIn);}
$word.append($i);});$word.css('opacity',1);});},_animateHeadline:function(){var self=this,animationType=self.settings.animation_type,dynamicWrapper=$(self.dynamicWrapper);if('clip'===animationType){dynamicWrapper.width(dynamicWrapper.width()+10);}else if('typing'!==animationType){var width=0;self.elements.dynamicText.each(function(){var wordWidth=$(this).width();if(wordWidth>width){width=wordWidth;}});dynamicWrapper.css('width',width);}
setTimeout(function(){self._hideWord(self.elements.dynamicText.eq(0));},self.animationDelay);},_showLetter:function($letter,$word,bool,duration){var self=this,classes=self.classes,animationType=self.settings.animation_type;$letter.addClass(classes.animationIn);if(!$letter.is(':last-child')){setTimeout(function(){self._showLetter($letter.next(),$word,bool,duration);},duration);}else{if(!bool){setTimeout(function(){self._hideWord($word);},self.animationDelay);}}},_hideLetter:function($letter,$word,bool,duration){var self=this;$letter.removeClass(self.classes.animationIn);if(!$letter.is(':last-child')){setTimeout(function(){self._hideLetter($letter.next(),$word,bool,duration);},duration);}else if(bool){setTimeout(function(){self._hideWord(self._getNextWord($word));},self.animationDelay);}},_showWord:function($word,duration){var self=this,animationType=self.settings.animation_type;if('typing'===animationType){self._showLetter($word.find('i').eq(0),$word,false,duration);$word.addClass(self.classes.textActive).removeClass(self.classes.textInactive);}else if('clip'===animationType){$(self.dynamicWrapper).animate({'width':$word.width()+10},self.revealDuration,function(){setTimeout(function(){self._hideWord($word);},self.revealAnimationDelay);});}},_hideWord:function($word){var self=this,classes=self.classes,animationType=self.settings.animation_type,nextWord=self._getNextWord($word);if('typing'===animationType){$(self.dynamicWrapper).addClass(classes.typeSelected);setTimeout(function(){$(self.dynamicWrapper).removeClass(classes.typeSelected);$word.addClass(classes.textInactive).removeClass(classes.textActive).children('i').removeClass(classes.animationIn);},self.selectionDuration);setTimeout(function(){self._showWord(nextWord,self.typeLettersDelay);},self.typeAnimationDelay);}else if($(self.headline).hasClass(classes.letters)){var bool=$word.children('i').length>=nextWord.children('i').length;self._hideLetter($word.find('i').eq(0),$word,bool,self.lettersDelay);self._showLetter(nextWord.find('i').eq(0),nextWord,bool,self.lettersDelay);}else if('clip'===animationType){$(self.dynamicWrapper).animate({width:'2px'},self.revealDuration,function(){self._switchWord($word,nextWord);self._showWord(nextWord);});}else{self._switchWord($word,nextWord);setTimeout(function(){self._hideWord(nextWord);},self.animationDelay);}},_getNextWord:function($word)
{return $word.is(':last-child')?$word.parent().children().eq(0):$word.next();},_switchWord:function($oldWord,$newWord)
{$oldWord.removeClass('pp-headline-text-active').addClass('pp-headline-text-inactive');$newWord.removeClass('pp-headline-text-inactive').addClass('pp-headline-text-active');},_getSvgPaths:function(pathName){var pathsInfo=this.svgPaths[pathName],$paths=jQuery();pathsInfo.forEach(function(pathInfo){$paths=$paths.add($('<path>',{d:pathInfo}));});return $paths;},};})(jQuery);;(function($){new PPAnimatedHeadlines({id:'5b76f7628cd59',headline_style:'highlight',rotating_text:'Awesome|Creative|Rotating',highlighted_text:'12th February 2019',headline_shape:'underline_zigzag',animation_type:'typing',});})(jQuery);jQuery(function($){$(function(){$('.fl-node-5b460a23570e7 .fl-photo-img').on('mouseenter',function(e){$(this).data('title',$(this).attr('title')).removeAttr('title');}).on('mouseleave',function(e){$(this).attr('title',$(this).data('title')).data('title',null);});});});(function($){$('.fl-node-5b460e615f622 .pp-infobox').on('mouseenter',function(){$('.fl-node-5b460e615f622 .pp-icon-wrapper').addClass(' none');});$('.fl-node-5b460e615f622 .pp-infobox').on('mouseleave',function(){$('.fl-node-5b460e615f622 .pp-icon-wrapper').removeClass(' none');});})(jQuery);jQuery(function($){$(function(){$('.fl-node-5b460a2357125 .fl-photo-img').on('mouseenter',function(e){$(this).data('title',$(this).attr('title')).removeAttr('title');}).on('mouseleave',function(e){$(this).attr('title',$(this).data('title')).data('title',null);});});});(function($){$('.fl-node-5b461af6c1551 .pp-infobox').on('mouseenter',function(){$('.fl-node-5b461af6c1551 .pp-icon-wrapper').addClass(' none');});$('.fl-node-5b461af6c1551 .pp-infobox').on('mouseleave',function(){$('.fl-node-5b461af6c1551 .pp-icon-wrapper').removeClass(' none');});})(jQuery);(function($){$('.fl-node-5b461b924a685 .pp-infobox').on('mouseenter',function(){$('.fl-node-5b461b924a685 .pp-icon-wrapper').addClass(' none');});$('.fl-node-5b461b924a685 .pp-infobox').on('mouseleave',function(){$('.fl-node-5b461b924a685 .pp-icon-wrapper').removeClass(' none');});})(jQuery);(function($){$('.fl-node-5b461b5938e96 .pp-infobox').on('mouseenter',function(){$('.fl-node-5b461b5938e96 .pp-icon-wrapper').addClass(' none');});$('.fl-node-5b461b5938e96 .pp-infobox').on('mouseleave',function(){$('.fl-node-5b461b5938e96 .pp-icon-wrapper').removeClass(' none');});})(jQuery);(function($){function equalheight(){if(window.navigator.userAgent.indexOf('MSIE ')>0){return;}
var maxHeight=0;$('.fl-node-5b46193496d34 .pp-logos-wrapper .pp-logo').each(function(index){if(($(this).find('.logo-image').outerHeight()+120)>maxHeight){maxHeight=$(this).find('.logo-image').outerHeight()+120;}});$('.fl-node-5b46193496d34 .pp-logos-wrapper .pp-logo').css('height',maxHeight+'px');return maxHeight;}
$('.fl-node-5b46193496d34 .pp-logos-wrapper').imagesLoaded(function(){equalheight();});})(jQuery);(function($){$('.fl-node-5b4618ce73c78 .pp-infobox').on('mouseenter',function(){$('.fl-node-5b4618ce73c78 .pp-icon-wrapper').addClass(' none');});$('.fl-node-5b4618ce73c78 .pp-infobox').on('mouseleave',function(){$('.fl-node-5b4618ce73c78 .pp-icon-wrapper').removeClass(' none');});})(jQuery);(function($){$('.fl-node-5b4674e897c22 .pp-infobox').on('mouseenter',function(){$('.fl-node-5b4674e897c22 .pp-icon-wrapper').addClass(' none');});$('.fl-node-5b4674e897c22 .pp-infobox').on('mouseleave',function(){$('.fl-node-5b4674e897c22 .pp-icon-wrapper').removeClass(' none');});})(jQuery);